GET http://localhost:3000/patient HTTP/1.1

###

POST http://localhost:3000/patient HTTP/1.1
content-type: application/json

{
    "name": "add name here",
    "age": "add age here" ,
	"email": "add email here",
	"password": "add password here",
    "physician": "add physician here"
}

###

DELETE http://localhost:3000/patient/5f962341a445631ef46d18a3 HTTP/1.1

###
